const customErrors = require("../utils/error");
const saleDatabase = require('../database/sale');


const updateSale = async(req)=>{
    try {
        
    } catch (error) {
        
    }
}
const     deleteSale = async(req)=>{
    try {
        
    } catch (error) {
        
    }
}
const     createSale = async(req)=>{
    try {
        
    } catch (error) {
        
    }
}
const     getOneSale = async(req)=>{
    try {
        
    } catch (error) {
        
    }
}
const     getAllSales = async(req)=>{
    try {
        
    } catch (error) {
        
    }
}



module.exports={
    updateSale,
    deleteSale,
    createSale,
    getOneSale,
    getAllSales

}